In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('./Water_FINAL.csv', low_memory=False)

In [5]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Agency,BiasPC,CloudCover,Comments,Cruise,Database,Date,FieldActivityEventType,...,Weather Conditions Yesterday,WindDirection,WindSpeed,state,Point,HUC12_,HUCNAME_,FIPS_,COUNTY_,STATE_
0,0,2143,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.93002800000002 39.480194),20600020206,Bohemia River,24015,Cecil County,MD
1,1,2145,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.902528 39.480444),20600020206,Bohemia River,24015,Cecil County,MD
2,2,2147,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,S,1-10 knots,MD,POINT (-75.873639 39.466889),20600020206,Bohemia River,24015,Cecil County,MD
3,3,2151,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.854444 39.454),20600020206,Bohemia River,24015,Cecil County,MD
4,4,2152,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.84352800000001 39.463667),20600020206,Bohemia River,24015,Cecil County,MD

In [6]:
df.shape

(2708717, 73)

In [7]:
df.size

197736341

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708717 entries, 0 to 2708716
Data columns (total 73 columns):
Unnamed: 0                                 int64
Unnamed: 0.1                               int64
Agency                                     object
BiasPC                                     object
CloudCover                                 object
Comments                                   object
Cruise                                     object
Database                                   object
Date                                       object
FieldActivityEventType                     object
FieldActivityRemark                        float64
FlowStage                                  object
GaugeHeight                                float64
GroupCode                                  object
HUC12                                      float64
Lab                                        object
Latitude                                   float64
Layer                                      object
Longitude                                  float64
LowerPycnocline                            float64
MeasureValue                               float64
Method                                     object
ModifiedDate                               object
Other Comments                             object
Other Conditions                           object
Parameter                                  object
ParameterName_CBP                          object
ParameterName_CMC                          object
PrecipType                                 object
PrecisionPC                                float64
Pressure                                   float64
Problem                                    object
Program                                    object
Project                                    object
Qualifier                                  object
Rainfall                                   object
Rainfall Within 24 Hours                   object
Rainfall Within 48 Hours                   object
SampleDepth                                float64
SampleId                                   float64
SampleReplicateType                        object
SampleType                                 object
Sea State                                  object
Source                                     object
Station                                    object
StationCode                                object
StationName                                object
Stream Flow                                object
Tidal Stage                                object
TideStage                                  object
TierLevel                                  object
Time                                       object
TotalDepth                                 float64
Unit                                       object
UpperPycnocline                            float64
Water Color                                object
Water Color Description                    object
Water Odor                                 object
Water Odor Description                     object
Water Surfaces                             object
WaveHeight                                 object
Weather Conditions Day Before Yesterday    object
Weather Conditions Today                   object
Weather Conditions Yesterday               object
WindDirection                              object
WindSpeed                                  object
state                                      object
Point                                      object
HUC12_                                     int64
HUCNAME_                                   object
FIPS_                                      int64
COUNTY_                                    object
STATE_                                     object
dtypes: float64(13), int64(4), object(56)
memory usage: 1.5+ GB

In [9]:
df_copy = df.copy()

In [10]:
# view missing values
df_copy = df_copy.dropna(axis=1 , how='all')

In [11]:
df_copy.head()

,Unnamed: 0,Unnamed: 0.1,Agency,BiasPC,CloudCover,Comments,Cruise,Database,Date,FieldActivityEventType,...,Weather Conditions Yesterday,WindDirection,WindSpeed,state,Point,HUC12_,HUCNAME_,FIPS_,COUNTY_,STATE_
0,0,2143,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.93002800000002 39.480194),20600020206,Bohemia River,24015,Cecil County,MD
1,1,2145,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,W,1-10 knots,MD,POINT (-75.902528 39.480444),20600020206,Bohemia River,24015,Cecil County,MD
2,2,2147,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,S,1-10 knots,MD,POINT (-75.873639 39.466889),20600020206,Bohemia River,24015,Cecil County,MD
3,3,2151,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.854444 39.454),20600020206,Bohemia River,24015,Cecil County,MD
4,4,2152,NaN,NaN,NaN,NaN,NaN,CMC,04/28/2018,NaN,...,NaN,SW,1-10 knots,MD,POINT (-75.84352800000001 39.463667),20600020206,Bohemia River,24015,Cecil County,MD

In [12]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708717 entries, 0 to 2708716
Data columns (total 71 columns):
Unnamed: 0                                 int64
Unnamed: 0.1                               int64
Agency                                     object
BiasPC                                     object
CloudCover                                 object
Comments                                   object
Cruise                                     object
Database                                   object
Date                                       object
FieldActivityEventType                     object
FlowStage                                  object
GaugeHeight                                float64
GroupCode                                  object
HUC12                                      float64
Lab                                        object
Latitude                                   float64
Layer                                      object
Longitude                                  float64
LowerPycnocline                            float64
MeasureValue                               float64
Method                                     object
ModifiedDate                               object
Other Comments                             object
Other Conditions                           object
Parameter                                  object
ParameterName_CBP                          object
ParameterName_CMC                          object
PrecipType                                 object
Pressure                                   float64
Problem                                    object
Program                                    object
Project                                    object
Qualifier                                  object
Rainfall                                   object
Rainfall Within 24 Hours                   object
Rainfall Within 48 Hours                   object
SampleDepth                                float64
SampleId                                   float64
SampleReplicateType                        object
SampleType                                 object
Sea State                                  object
Source                                     object
Station                                    object
StationCode                                object
StationName                                object
Stream Flow                                object
Tidal Stage                                object
TideStage                                  object
TierLevel                                  object
Time                                       object
TotalDepth                                 float64
Unit                                       object
UpperPycnocline                            float64
Water Color                                object
Water Color Description                    object
Water Odor                                 object
Water Odor Description                     object
Water Surfaces                             object
WaveHeight                                 object
Weather Conditions Day Before Yesterday    object
Weather Conditions Today                   object
Weather Conditions Yesterday               object
WindDirection                              object
WindSpeed                                  object
state                                      object
Point                                      object
HUC12_                                     int64
HUCNAME_                                   object
FIPS_                                      int64
COUNTY_                                    object
STATE_                                     object
dtypes: float64(11), int64(4), object(56)
memory usage: 1.4+ GB

In [13]:
# find duplicates
df_copy[df_copy.duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 0.1, Agency, BiasPC, CloudCover, Comments, Cruise, Database, Date, FieldActivityEventType, FlowStage, GaugeHeight, GroupCode, HUC12, Lab, Latitude, Layer, Longitude, LowerPycnocline, MeasureValue, Method, ModifiedDate, Other Comments, Other Conditions, Parameter, ParameterName_CBP, ParameterName_CMC, PrecipType, Pressure, Problem, Program, Project, Qualifier, Rainfall, Rainfall Within 24 Hours, Rainfall Within 48 Hours, SampleDepth, SampleId, SampleReplicateType, SampleType, Sea State, Source, Station, StationCode, StationName, Stream Flow, Tidal Stage, TideStage, TierLevel, Time, TotalDepth, Unit, UpperPycnocline, Water Color, Water Color Description, Water Odor, Water Odor Description, Water Surfaces, WaveHeight, Weather Conditions Day Before Yesterday, Weather Conditions Today, Weather Conditions Yesterday, WindDirection, WindSpeed, state, Point, HUC12_, HUCNAME_, FIPS_, COUNTY_, STATE_]
Index: []

[0 rows x 71 columns]

In [14]:
# Drop rows full of missing values
df_copy = df_copy.dropna(axis=0, how="all")

In [15]:
df_copy.shape

(2708717, 71)

In [16]:
# Select Columns of Interest
selected_df = df_copy[['Date', 'Database', 'Latitude', 'Longitude', 'MeasureValue', 'ModifiedDate', 'Parameter', 'ParameterName_CBP', 'ParameterName_CMC',
                       'StationName', 'Stream Flow', 'Time','Unit', 'WindSpeed', 'WindDirection', 'state', 'HUCNAME_']]

In [17]:
# view selected columns
selected_df.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
0,04/28/2018,CMC,39.480194,-75.930028,14.970,2020-04-25T17:31:58.767,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT01,NaN,12:05:00,ug/L,1-10 knots,W,MD,Bohemia River
1,04/28/2018,CMC,39.480444,-75.902528,20.002,2020-04-25T17:31:59.173,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT02,NaN,12:40:00,ug/L,1-10 knots,W,MD,Bohemia River
2,04/28/2018,CMC,39.466889,-75.873639,26.204,2020-04-25T17:31:59.36,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT03,NaN,13:13:00,ug/L,1-10 knots,S,MD,Bohemia River
3,04/28/2018,CMC,39.454000,-75.854444,47.652,2020-04-25T17:31:59.627,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT04,NaN,13:53:00,ug/L,1-10 knots,SW,MD,Bohemia River
4,04/28/2018,CMC,39.463667,-75.843528,38.820,2020-04-25T17:31:59.937,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT05,NaN,14:24:00,ug/L,1-10 knots,SW,MD,Bohemia River

In [20]:
selected_df['Database'].unique()

array(['CMC', 'CBP'], dtype=object)

In [18]:
selected_df['ParameterName_CBP'].unique()

array(['ACTIVE CHLOROPHYLL-A',
       'DO SATURATION USING PROBE UNITS IN PERCENT',
       'Not in CBP Database',
       'SALINITY UNITS IN PPT AND EQUAL TO PRACTICAL SALNITY UNITS (PSU)',
       'DISSOLVED OXYGEN IN MG/L',
       'NITRATE NITROGEN AS N (FILTERED SAMPLE)', 'SECCHI DEPTH',
       'WATER TEMPERATURE DEG', 'PH CORRECTED FOR TEMPERATURE (25 DEG C)',
       'SPECIFIC CONDUCTIVITY', 'AIR TEMPERATURE DEG',
       'AMMONIUM NITROGEN AS N (FILTERED SAMPLE)', 'E.COLI BACTERIA',
       'TOTAL PHOSPHORUS',
       'ORTHOPHOSPHATE PHOSPHORUS AS P (FILTERED SAMPLE)',
       'TOTAL DISSOLVED SOLIDS; GRAVIMETRIC; DRIED AT 180 C',
       'TURBIDITY; JACKSON CANDLE METHOD (FORWARD SCATTER)',
       'TURBIDITY; NEPHELOMETRIC METHOD', 'TOTAL DEPTH',
       'TOTAL SUSPENDED SOLIDS', 'TOTAL ALKALINITY AS CACO3',
       'TURBIDITY TUBE', 'TOTAL NITROGEN',
       'TOTAL KJELDAHL NITROGEN (WHOLE SAMPLE)'], dtype=object)

In [19]:
selected_df['ParameterName_CMC'].unique()

array(['Chlorophyll a;b;c ', 'Dissolved oxygen % Sat ',
       'Nitrate-nitrogen ', 'Salinity ', 'Dissolved oxygen ',
       'Water Clarity ', 'Water temperature ', 'pH ', 'Conductivity ',
       'Air temperature ', 'Orthophosphate ', 'Ammonia-nitrogen ',
       'Air Temperature ', 'Chlorophyll a ', 'Bacteria [E.Coli] ',
       'Total Phosphorus ', 'Total Dissolved Solids ', 'Enterococcus ',
       'Total Depth ', 'Total Suspended Solids ', 'Alkalinity ',
       'Nitrite-nitrate ', 'Dissolved Oxygen % Sat ', 'Total Nitrogen ',
       'Total Kjeldahl Nitrogen ', 'Water Temperature ', nan],
      dtype=object)

In [21]:
# Select rows of data taken from CMC
CMC_df = selected_df[selected_df['Database'] == 'CMC']

In [22]:
CMC_df.shape

(264261, 20)

In [23]:
CMC_df.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
0,04/28/2018,CMC,39.480194,-75.930028,14.970,2020-04-25T17:31:58.767,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT01,NaN,12:05:00,ug/L,1-10 knots,W,MD,Bohemia River
1,04/28/2018,CMC,39.480444,-75.902528,20.002,2020-04-25T17:31:59.173,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT02,NaN,12:40:00,ug/L,1-10 knots,W,MD,Bohemia River
2,04/28/2018,CMC,39.466889,-75.873639,26.204,2020-04-25T17:31:59.36,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT03,NaN,13:13:00,ug/L,1-10 knots,S,MD,Bohemia River
3,04/28/2018,CMC,39.454000,-75.854444,47.652,2020-04-25T17:31:59.627,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT04,NaN,13:53:00,ug/L,1-10 knots,SW,MD,Bohemia River
4,04/28/2018,CMC,39.463667,-75.843528,38.820,2020-04-25T17:31:59.937,CHL.3,ACTIVE CHLOROPHYLL-A,Chlorophyll a;b;c,NaN,NaN,NaN,FOB BT05,NaN,14:24:00,ug/L,1-10 knots,SW,MD,Bohemia River

In [24]:
# Select rows of data taken from CBP
CBP_df = selected_df[selected_df['Database'] == 'CBP']

In [25]:
# Size of data from CBP
CBP_df.shape

(2444456, 20)

## Do some Data Cleaning on selected_df

In [26]:
# Strip white space from Parameter, ParameterName_CBP and ParameterName_CMC
selected_df['ParameterName_CBP'] = selected_df['ParameterName_CBP'].str.strip()

/home/mupati/anaconda3/envs/datascience/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [30]:
selected_df['ParameterName_CMC'] = selected_df['ParameterName_CMC'].str.strip()

/home/mupati/anaconda3/envs/datascience/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [31]:
selected_df['ParameterName_CMC'].unique()

array(['Chlorophyll a;b;c', 'Dissolved oxygen % Sat', 'Nitrate-nitrogen',
       'Salinity', 'Dissolved oxygen', 'Water Clarity',
       'Water temperature', 'pH', 'Conductivity', 'Air temperature',
       'Orthophosphate', 'Ammonia-nitrogen', 'Air Temperature',
       'Chlorophyll a', 'Bacteria [E.Coli]', 'Total Phosphorus',
       'Total Dissolved Solids', 'Enterococcus', 'Total Depth',
       'Total Suspended Solids', 'Alkalinity', 'Nitrite-nitrate',
       'Dissolved Oxygen % Sat', 'Total Nitrogen',
       'Total Kjeldahl Nitrogen', 'Water Temperature', nan], dtype=object)

In [35]:
selected_df.query('ParameterName_CMC == "Chlorophyll a;b;c"  or ParameterName_CMC == "Chlorophyll a"')['ParameterName_CMC'].value_counts()

Chlorophyll a        4463
Chlorophyll a;b;c     177
Name: ParameterName_CMC, dtype: int64

In [52]:
# Standardize Parameter Values
# 'Dissolved oxygen % Sat' and 'Dissolved Oxygen % Sat' = 'Dissolved Oxygen % Sat'
# 'Air temperature' and 'Air Temperature' = 'Air Temperature'
# 'Water Temperature' and 'Water temperature' = 'Water Temperature'
# 'Chlorophyll a;b;c' and 'Chlorophyll a' = 'Chlorophyll A'
# Bacteria [E.Coli] = 'E.coli'

# Errorneous values
# Nitrite-nitrate = 'Nitrate-nitrogen'

In [40]:
# Replace 'Nitrate-nitrate' with 'Nitrate-nitrogen'
selected_df['ParameterName_CMC'] = selected_df['ParameterName_CMC'].replace({
    'Nitrite-nitrate':'Nitrate-nitrogen',
    'Air temperature': 'Air Temperature',
    'Dissolved oxygen % Sat': 'Dissolved Oxygen % Sat',
    'Water temperature': 'Water Temperature',
    'Chlorophyll a;b;c': 'Chlorophyll A',
    'Chlorophyll a': 'Chlorophyll A'
    })

/home/mupati/anaconda3/envs/datascience/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [41]:
selected_df['ParameterName_CMC'].unique()

array(['Chlorophyll A', 'Dissolved Oxygen % Sat', 'Nitrate-nitrogen',
       'Salinity', 'Dissolved oxygen', 'Water Clarity',
       'Water Temperature', 'pH', 'Conductivity', 'Air Temperature',
       'Orthophosphate', 'Ammonia-nitrogen', 'Bacteria [E.Coli]',
       'Total Phosphorus', 'Total Dissolved Solids', 'Enterococcus',
       'Total Depth', 'Total Suspended Solids', 'Alkalinity',
       'Total Nitrogen', 'Total Kjeldahl Nitrogen', nan], dtype=object)

### Create Dataframes for each parameter of interest from the selected_df
##### Features of interest
* Water Temperature
* pH
* Air Temperature
* Dissolved Oxygen
* Precipitation
* Bacteria <br/>

 air temperature, stream temperature, precipitation, river floods, and sea level rise<br/>
 Water temperature, for instance, can impact the abundance and distribution of underwater grasses and the stream habitat available to brook trout.

In [42]:
water_temp = selected_df.query('ParameterName_CMC == "Water Temperature"')

In [43]:
water_temp.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
14572,01/01/2012,CMC,38.289800,-77.481600,9.0,2020-04-15T14:35:09.607,WT.8,WATER TEMPERATURE DEG,Water Temperature,NaN,NaN,NaN,FOR1,Normal,13:45:00,deg C,NaN,NaN,VA,Hazel Run-Rappahannock River
14573,01/01/2014,CMC,37.923634,-76.720680,6.0,2020-03-10T11:04:49.987,WT.8,WATER TEMPERATURE DEG,Water Temperature,NaN,NaN,NaN,TOT3,Normal,10:20:00,deg C,NaN,NaN,VA,Totuskey Creek
14574,01/01/2014,CMC,37.886036,-76.736281,6.0,2020-03-10T11:16:13.723,WT.8,WATER TEMPERATURE DEG,Water Temperature,NaN,NaN,NaN,TOT4,Normal,10:30:00,deg C,NaN,NaN,VA,Totuskey Creek
14575,01/01/2014,CMC,37.926034,-76.709080,6.0,2020-03-10T11:04:35.813,WT.8,WATER TEMPERATURE DEG,Water Temperature,NaN,NaN,NaN,TOT2,Normal,12:31:00,deg C,NaN,NaN,VA,Totuskey Creek
14576,01/01/2014,CMC,37.912934,-76.657379,5.0,2020-03-10T11:04:18.423,WT.8,WATER TEMPERATURE DEG,Water Temperature,NaN,NaN,NaN,TOT1,Normal,22:17:00,deg C,NaN,NaN,VA,Totuskey Creek

In [44]:
pH = selected_df.query('ParameterName_CMC == "pH"')

In [45]:
pH.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
15295,03/15/2018,CMC,38.86972,-77.00292,7.00,2018-10-16T19:24:43.963,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,NaN,NaN,NaN,Ana-PP,NaN,13:06:00,SU,NaN,NaN,DC,Lower Anacostia River
15296,04/16/2018,CMC,38.86972,-77.00292,7.00,2018-10-16T19:37:08.757,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,NaN,NaN,NaN,Ana-PP,NaN,14:02:00,SU,NaN,NaN,DC,Lower Anacostia River
15297,04/30/2018,CMC,38.86972,-77.00292,6.80,2018-10-16T19:36:53.35,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,NaN,NaN,NaN,Ana-PP,NaN,14:59:00,SU,NaN,NaN,DC,Lower Anacostia River
15298,06/29/2018,CMC,38.86972,-77.00292,6.75,2018-10-24T10:51:47.923,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,NaN,NaN,NaN,Ana-PP,NaN,14:24:49,SU,NaN,NaN,DC,Lower Anacostia River
15299,09/27/2018,CMC,38.86972,-77.00292,7.30,2018-10-24T10:37:54.563,PH.6,PH CORRECTED FOR TEMPERATURE (25 DEG C),pH,NaN,NaN,NaN,Ana-PP,NaN,13:41:02,SU,NaN,NaN,DC,Lower Anacostia River

In [46]:
air_temp = selected_df.query('ParameterName_CMC == "Air Temperature"')

In [47]:
air_temp.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
18338,01/06/2020,CMC,39.023611,-76.265556,6.0,2020-01-14T10:28:14.143,AT.3,AIR TEMPERATURE DEG,Air Temperature,NaN,Calm,NaN,0404019A,NaN,08:30:00,deg C,1-10 knots,SW,MD,Lower Chester River
18339,01/06/2020,CMC,39.154440,-76.068060,6.0,2020-01-14T10:28:14.707,AT.3,AIR TEMPERATURE DEG,Air Temperature,NaN,Calm,NaN,0401002,NaN,09:38:00,deg C,1-10 knots,SW,MD,Middle Chester River
18340,01/06/2020,CMC,39.087500,-76.165556,6.0,2020-01-14T10:28:14.923,AT.3,AIR TEMPERATURE DEG,Air Temperature,NaN,Calm,NaN,0403004A,NaN,09:56:00,deg C,1-10 knots,SW,MD,Lower Chester River
18341,01/07/2020,CMC,38.842222,-76.303611,3.0,2020-01-14T10:39:51.02,AT.3,AIR TEMPERATURE DEG,Air Temperature,NaN,Calm,NaN,0804014,NaN,09:19:00,deg C,1-10 knots,SW,MD,Eastern Bay
18342,01/07/2020,CMC,38.898333,-76.313333,3.0,2020-01-14T10:39:51.27,AT.3,AIR TEMPERATURE DEG,Air Temperature,NaN,Calm,NaN,0804019,NaN,09:55:00,deg C,1-10 knots,SW,MD,Cox Creek-Frontal Eastern Bay

In [48]:
dissolved_oxygen = selected_df.query('ParameterName_CMC == "Dissolved oxygen"')

In [49]:
dissolved_oxygen.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
5528,03/24/2019,CMC,38.6336,-75.6177,10.6,2020-01-10T10:23:35.937,DO.5,DISSOLVED OXYGEN IN MG/L,Dissolved oxygen,NaN,NaN,NaN,DENA2,NaN,12:28:00,mg/L,NaN,NaN,DE,Butler Mill Branch-Nanticoke River
5529,03/24/2019,CMC,38.6422,-75.6068,11.0,2020-01-08T15:05:47.07,DO.5,DISSOLVED OXYGEN IN MG/L,Dissolved oxygen,NaN,NaN,NaN,COBR1,NaN,12:46:00,mg/L,NaN,NaN,DE,Clear Brook-Turkey Branch
5530,03/24/2019,CMC,38.6013,-75.6563,11.0,2020-01-10T11:34:58.147,DO.5,DISSOLVED OXYGEN IN MG/L,Dissolved oxygen,NaN,NaN,NaN,DENA4,NaN,13:05:00,mg/L,NaN,NaN,DE,Butler Mill Branch-Nanticoke River
5531,03/24/2019,CMC,38.6013,-75.6563,10.9,2020-01-10T11:34:58.147,DO.5,DISSOLVED OXYGEN IN MG/L,Dissolved oxygen,NaN,NaN,NaN,DENA4,NaN,13:05:00,mg/L,NaN,NaN,DE,Butler Mill Branch-Nanticoke River
5532,03/24/2019,CMC,38.6013,-75.6563,10.9,2020-01-10T11:34:58.147,DO.5,DISSOLVED OXYGEN IN MG/L,Dissolved oxygen,NaN,NaN,NaN,DENA4,NaN,13:05:00,mg/L,NaN,NaN,DE,Butler Mill Branch-Nanticoke River

In [50]:
conductivity =  selected_df.query('ParameterName_CMC == "Conductivity"')

In [51]:
conductivity.head()

,Date,Database,Latitude,Longitude,MeasureValue,ModifiedDate,Parameter,ParameterName_CBP,ParameterName_CMC,Rainfall,Sea State,Source,StationName,Stream Flow,Time,Unit,WindSpeed,WindDirection,state,HUCNAME_
15360,01/09/2019,CMC,39.661800,-76.147400,200.0,2020-03-24T09:49:40.857,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,NaN,NaN,NaN,Basin Run,NaN,08:45:00,uS/cm,NaN,NaN,MD,Basin Run-Octoraro Creek
15361,01/09/2019,CMC,39.702983,-76.109467,232.0,2020-03-24T09:49:40.17,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,NaN,NaN,NaN,Stone Run,NaN,09:05:00,uS/cm,NaN,NaN,MD,Basin Run-Octoraro Creek
15362,01/09/2019,CMC,39.706667,-76.115556,264.0,2020-03-24T09:49:38.873,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,NaN,NaN,NaN,Octoraro Mainstem,NaN,09:30:00,uS/cm,NaN,NaN,MD,Tweed Creek-Octoraro Creek
15363,01/09/2019,CMC,39.659947,-76.152979,260.0,2020-03-24T09:49:39.513,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,NaN,NaN,NaN,Octoraro Mainstem,NaN,09:45:00,uS/cm,NaN,NaN,MD,Basin Run-Octoraro Creek
15364,01/14/2020,CMC,39.661800,-76.147400,237.0,2020-03-24T09:46:42.623,CO.8,SPECIFIC CONDUCTIVITY,Conductivity,NaN,NaN,NaN,Basin Run,NaN,08:15:00,uS/cm,NaN,NaN,MD,Basin Run-Octoraro Creek